# Generated by Django 4.0.2 on 2022-03-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_function_pages', '0002_auto_20220326_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('approve_project', 'Can approve projects')]},
        ),
    ]
