# Generated by Django 3.1 on 2022-04-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('unapproved', 'Not Approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unapproved', help_text='The approval status of this project', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the project', null=True),
        ),
    ]
