# Generated by Django 4.0.3 on 2022-04-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_approval_status'),
        ('projects', '0002_project_approval_status_alter_project_description'),
    ]

    operations = [
    ]
